SET DB_CLOSE_DELAY -1;        
;             
CREATE USER IF NOT EXISTS SA SALT '8661bedfc60bfddd' HASH 'de619aa0bcb1050bb0790236b8db13969db562dd41cfa9d5372ba020f35ea9f7' ADMIN;           
CREATE SEQUENCE PUBLIC.HIBERNATE_SEQUENCE START WITH 33;      
CREATE CACHED TABLE PUBLIC.COMMENT(
    ID BIGINT NOT NULL,
    AUTHORUSERNAME VARCHAR(255),
    POSTED TIMESTAMP,
    TEXT VARCHAR(255)
);              
ALTER TABLE PUBLIC.COMMENT ADD CONSTRAINT PUBLIC.CONSTRAINT_6 PRIMARY KEY(ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.COMMENT; 
CREATE CACHED TABLE PUBLIC.COMMENT_COMMENT(
    COMMENT_ID BIGINT NOT NULL,
    COMMENTREPLY_ID BIGINT NOT NULL
);         
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.COMMENT_COMMENT;         
CREATE CACHED TABLE PUBLIC.TICKET(
    ID BIGINT NOT NULL,
    AREA VARCHAR(255),
    CREATED TIMESTAMP,
    CREATOR VARCHAR(255),
    DESCRIPTION VARCHAR(255),
    MODIFIED TIMESTAMP,
    OWNER VARCHAR(255),
    PRIORITY VARCHAR(255),
    STATUS VARCHAR(255)
);              
ALTER TABLE PUBLIC.TICKET ADD CONSTRAINT PUBLIC.CONSTRAINT_9 PRIMARY KEY(ID); 
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TICKET;  
CREATE CACHED TABLE PUBLIC.TICKET_COMMENT(
    TICKET_ID BIGINT NOT NULL,
    TICKETCOMMENT_ID BIGINT NOT NULL
);          
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TICKET_COMMENT;          
CREATE CACHED TABLE PUBLIC.USER(
    ID BIGINT NOT NULL,
    AREA VARCHAR(25),
    NAME VARCHAR(25),
    PASSWORD VARCHAR(255),
    PROFILE VARCHAR(255),
    STATUS VARCHAR(255),
    USERNAME VARCHAR(255)
);              
ALTER TABLE PUBLIC.USER ADD CONSTRAINT PUBLIC.CONSTRAINT_2 PRIMARY KEY(ID);   
-- 6 +/- SELECT COUNT(*) FROM PUBLIC.USER;    
INSERT INTO PUBLIC.USER(ID, AREA, NAME, PASSWORD, PROFILE, STATUS, USERNAME) VALUES
(1, 'Martin Diaz', 'Gestion','1234abcd', 'Admin', 'ACTIVE', 'u584110'),
(2, 'Yanina Chialchi', 'Gestion','1234abcd', 'Analist', 'ACTIVE', 'u584111'),
(3, 'Romina Bernasco', 'Externa','1234abcd', 'User', 'ACTIVE', 'u584112'),
(4, 'Carlos Berlusconi', 'Externa','1234abcd', 'User', 'ACTIVE', 'u584113'),
(5, 'Reina Isabel', 'Gestion','1234abcd', 'Analist', 'INACTIVE', 'u584114'),
(6, 'Julio Cesar', 'Externa','1234abcd', 'User', 'INACTIVE', 'u584115');   
ALTER TABLE PUBLIC.COMMENT_COMMENT ADD CONSTRAINT PUBLIC.UK_DQ7YM11ME0I24FQHGIT52EPWW UNIQUE(COMMENTREPLY_ID);
ALTER TABLE PUBLIC.TICKET_COMMENT ADD CONSTRAINT PUBLIC.UK_1SIM4K4PSBM352SB31HQ2IU0O UNIQUE(TICKETCOMMENT_ID);
ALTER TABLE PUBLIC.USER ADD CONSTRAINT PUBLIC.UK_HL8FFTX66P59OQGKKCFIT3EAY UNIQUE(USERNAME);  
ALTER TABLE PUBLIC.TICKET_COMMENT ADD CONSTRAINT PUBLIC.FKNI13GQBROS833RCVL97J2H98M FOREIGN KEY(TICKET_ID) REFERENCES PUBLIC.TICKET(ID) NOCHECK;              
ALTER TABLE PUBLIC.COMMENT_COMMENT ADD CONSTRAINT PUBLIC.FKO51R3KF9U24E8GSKTYBWOG66S FOREIGN KEY(COMMENT_ID) REFERENCES PUBLIC.COMMENT(ID) NOCHECK;           
ALTER TABLE PUBLIC.COMMENT_COMMENT ADD CONSTRAINT PUBLIC.FKKBMQX25TOTNWXEX9COV9NYBBH FOREIGN KEY(COMMENTREPLY_ID) REFERENCES PUBLIC.COMMENT(ID) NOCHECK;      
ALTER TABLE PUBLIC.TICKET_COMMENT ADD CONSTRAINT PUBLIC.FKR4ODAFQAX9HEFYEVGF59N6KRN FOREIGN KEY(TICKETCOMMENT_ID) REFERENCES PUBLIC.COMMENT(ID) NOCHECK;      
